### ISSUE TITLE
Translations and content fix

### ISSUE THREAD

**Issue by dominikstas** [dominikstas/etc#4]

**Comment by dominikstas** [comment]
And bold the text

**Comment by HlucaszH** [comment]
Fully translated, content fix, can now add bold text, underlined and so to the translation. Will keep it open as we make a new subpage to translate.

**Comment by dominikstas** [comment]
content to be fixed:
- white text on images
- about us page
- contact page

**Comment by dominikstas** [comment]
**closing all issues - completely new page soon**
